### ISSUE TITLE
Start Monitoring doesn't stop and download file if you "Leave" the Meet.

### ISSUE THREAD

**Issue by argosgold** [robol/save-participants-extension#1]
Due to connection problems, I left a meet I was administrating today. 
I had set the extension "Start Monitoring". 

On reconnecting, the extension had stopped monitoring but not downloaded the file of participants.

**Comment by robol** [comment]
Indeed, the tracking is currently saved in the page, so there is no persistence if one leaves the meeting. A better and more robust solution would be to use the local storage, so that an interrupted session can be continued later on.

That requires a few substantial changes, I will look into that.

**Comment by robol** [comment]
I changed to tracking to use local storage, now it allows to recover an interrupted session; I am happy to have feedback, if you use it (please note the extension is not yet published in the Chrome store, you will need to clone this repository and install it by enabling developer mode).
