### ISSUE TITLE
Google Meet update breaks participants list download

### ISSUE THREAD

**Issue by frazar** [robol/save-participants-extension#2]
It appears that the Google Meet interface has been updated recently, breaking support for exporting the list of participants.

In particular, I believe the element being selected [here](https://github.com/robol/save-participants-extension/blob/8a9e5d12ede706ae41ff376c290c941c7bb94ead/contentscript.js#L72) no longer exists. I think the selector could be updated to be something like `document.querySelector('[role="list"]')`.

**Comment by robol** [comment]
Thanks for reporting the issue. 

I will try to find some time to fix it, but I am very open to accept pull requests, in case you wish to prepare one.

**Comment by robol** [comment]
I tested it as well, I will release version 2.5 of the extension on the store today including this fix. Thanks!
