### ISSUE TITLE
Google Meets -  It will not work.

### ISSUE THREAD

**Issue by reynosooscar** [robol/save-participants-extension#4]
It will no longer take attendance since google meets made some new changes. Please fix!! I use it daily. - High School Teacher

**Comment by robol** [comment]
The bug has already been reported and fixed in #2. The new version will be available soon on the Chrome Web Store.

**Comment by reynosooscar** [comment]
Hello,
I have a usefull suggestion but first of all I would like to say "Thank you".  Your program is like old faithful. It always works! Other programs often have glitches and don't always function properly. Thats why now I only use yours exclusively.

My suggestion or rather petition would be if you could alphabetize the list by last name? Currently what I do is copy the list and then paste it on Excel or Google Slides. 

From there on **Excel** once the list is pasted I go to "DATA", I then go to "TEXT TO COLUMNS" I then check off "Delimited" and then "NEXT". I then check of "SPACE" then "NEXT" then "FINISH" This splits the name from first to last name.  I then use "SORT" A to Z on the second column and this alphabetizes the list . 

On Google Sheets I paste the list and then go to "DATA". I then go to "Split text to columns" , I then select "BY SPACE" this seperates the names from first and last name. I then select the second column and then choose "SORT SHEET"  A to Z on the second column. This Alphebetizes the list. 

This would be super helpful for us high school teachers who have multiple classes. I love the little list on Notepad but I doubt it can alphabetize.
Just a thought. Thank you for your time. :0)
